import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderBar from "@/components/header-bar";
import { Inria_Sans } from "next/font/google";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inriaFont = Inria_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inria-sans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inriaFont.variable} antialiased`}
      >
        <HeaderBar />
        {children}
        {/* <h1 className={`${inriaFont.className}`}>Let's See What Happens</h1> */}
        <h1 className="font-inriaSans">Lets see</h1>
        <Footer />
      </body>
    </html>
  );
}
